- hosts: all
  name: example1
  become: true
  tasks:
    - name: update Debian
      ansible.builtin.apt:
        update_cache: true
      when: ansible_os_family == 'Debian'

    - name: update RedHat
      ansible.builtin.yum:
        update_cache: true
      when: ansible_os_family == 'RedHat'

    - name: install python
      ansible.builtin.package:
        name: python3
        state: present
